<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HTFManager</AssemblyName>
    <RootNamespace>HTFManager.App</RootNamespace>
    <Version>0.3.8</Version>
    <FileVersion>0.3.8.0</FileVersion>
    <InformationalVersion>0.3.8</InformationalVersion>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HTFManager.Core\HTFManager.Core.csproj" />
    <ProjectReference Include="..\HTFManager.Infrastructure\HTFManager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**\*.*" />
    <AvaloniaResource Include="Localization\*.json" />
    <AvaloniaResource Include="Localization\ConfigSchemas\**\*.json" />
  </ItemGroup>
</Project>
